#!/bin/bash
#Compare the rpm database between two hosts

if [ $# -ne 2 ]; then
    echo "No hosts specified. usage: rpmcmp host1 host2"
    exit 1
fi

#Get first remote host rpm database
ssh -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $1 "rpm -qa" > /tmp/rpm_db1.$$

#Get second remote host rpm database
ssh -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $2 "rpm -qa" > /tmp/rpm_db2.$$

#Compare and display output
sdiff -s <(sort /tmp/rpm_db1.$$) <(sort /tmp/rpm_db2.$$)

#Remove tmp files
rm /tmp/rpm_db1.$$
rm /tmp/rpm_db2.$$
