#!/bin/sh
#Compare the rpm database between two systems

if [ $# -ne 2 ]; then
    echo "No servers specified"
    exit 1
fi

#Get remote server rpm database
ssh -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $1 "rpm -qa" > /tmp/rpm_db1.$$

#Get local rpm database
ssh -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $2 "rpm -qa" > /tmp/rpm_db2.$$
#rpm -qa > /tmp/local_server_rpm_db.$$

#Compare and display output
sdiff -s <(sort /tmp/rpm_db1.$$) <(sort /tmp/rpm_db2.$$)

#Remove tmp files
rm /tmp/rpm_db1.$$
rm /tmp/rpm_db2.$$
